// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormDisplayController from "./form_display_controller"
application.register("form-display", FormDisplayController)

import ListCardController from "./list_card_controller"
application.register("list-card", ListCardController)
